### ISSUE TITLE
Exception on request doOutcomesService with SSL certificate problem

### ISSUE THREAD

**Issue by alexber220** [celtic-project/LTI-PHP#20]
We use  LTI-PHP 4.5.0

Request doOutcomesService on url https://moodler2.bgpu.ru/mod/lti/service.php return Exception
DOMDocument::loadXML(): Argument #1 ($source) must not be empty
File: .../vendor/celtic/lti/src/ResourceLink.php; line: 1732

curl -d "" https://moodler2.bgpu.ru
say
curl: (60) SSL certificate problem: unable to get local issuer certificate

if append this lines
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
before
$chResp = curl_exec($ch);
in file celtic/lti/src/Http/CurlClient.php
resolve this problem.

How fix this problem?

**Comment by spvickers** [comment]
You are correct that the CurlClient code will seek to verify the SSL certificate when making https connections, which I would regard as best practice.  To avoid the issue you have encountered you could do one of the following:

1. disable the certificate check (as your sample code does)
2. use http rather than https
3. install a signed certificate on your server
4. try using the StreamClient instead (create an instance and use the HttpMessage::setHttpClient method for it to be used); I've not checked whether this bypasses certificate checks but suspect it might
5. define you own Http\ClientInterface class which disables the certificate check and set this as the default HTTP client

**Comment by alexber220** [comment]
Thank you. Is possible to display an error about an incorrect certificate in the you library?

**Comment by spvickers** [comment]
The error property of the HttpMessage object should give the reason for any error (for example, ResourceLink->lastServiceRequest->error).  However, I have also committed a change to add this value to the error log, as well as fixing an issue when curl returns a status of zero.

**Comment by alexber220** [comment]
excellent

**Comment by spvickers** [comment]
This change is included in the recent 4.5.1 release.
