### ISSUE TITLE
Help with basic integration

### ISSUE THREAD

**Issue by MarcosCifu** [celtic-project/LTI-PHP#23]
I'm trying to integrate this library with Laravel using the rating app but I can't save the basic information of the platform
![image](https://user-images.githubusercontent.com/8668878/149995751-e6966e2d-2c20-4fd0-ae79-af0880ae1300.png)
I would be very grateful if you could guide me

**Comment by spvickers** [comment]
Sorry, I am not familiar with the Laravel framework, but I do notice that your code is setting the database tablename prefix to be "DB_TABLENAME_PREFIX", rather than the value of the constant defined with this name.  Otherwise, all I can suggest is that you get the Rating code to work as-is first, and then adapt it as required to fit wth Laravel so you can see which change causes it to fail.

**Comment by chrispittman** [comment]
Hi, @spvickers.  Over at https://github.com/longhornopen/laravel-celtic-lti we're building a Laravel-specific wrapper for this library (which we're big fans of!) to handle things like database connection management in the opinionated way Laravel prefers.  This developer also opened an issue over there and we've helped him out.  FYI and thanks!

**Comment by MarcosCifu** [comment]
I'm sorry for the spam, I'm having a hard time understanding but I'm making progress little by little. thank you

**Comment by spvickers** [comment]
@chrispittman, thanks for the feedback.  Do let me know if you think there is a change I could make in this code which would make it easier for use with Laravel, whilst continuing to work as-is.
