### ISSUE TITLE
Update to PHP 8.1

### ISSUE THREAD

**Issue by spvickers** [celtic-project/LTI-PHP#40]
I am working on an update to this library to use the functionality available in PHP 8.1, such as:

- type hinting
- strict typing
- match expression
- enumerations

I propose that this will be released as version 5, with version 4 being placed in a security-update only mode.

If anyone has any suggestions for how this library can be improved then this would be a good time to report them.

Thanks.

**Comment by chrispittman** [comment]
The main thing that'd improve the library, in my opinion, is to use Exceptions to report errors, rather than passing an 'ok=false' value around.  When something goes wrong while developing with this library, rather than getting an exception with a stack trace pointing you to the line with the error (and the call history of how you got there), you've got to look at the string message you received, go digging in the code for the place that that string was generated, and try to work out how you got there and why.  In aggregate, that's eaten up a lot of development time.

**Comment by spvickers** [comment]
Thanks for the feedback.  The code is certainly a bit old-fashioned these days in its avoidance of using exceptions.  However, I would also be keen to ensure that the code remains backwards compatible.  Would you be able to give a specific example of a method or class where you experienced this issue?  I am assuming it was not within the private methods of the library.  Thanks.

**Comment by chrispittman** [comment]
Ah, if you're trying to maintain backwards compatibility, this idea is probably a bridge too far, then.  Please ignore!

(My specific case is from last year, when I'd accidentally called `Tool->handleRequest()` twice.  The second call was failing, because the request's nonce had already been consumed and deleted by the first call.  But figuring that out led me into a bunch of the library's private request-processing and nonce-handling methods, where having an exception's stack trace would have helped answer "How did I get to this point in the code?".)

**Comment by spvickers** [comment]
Thanks for the response.  I will keep this in mind just in case.
