### ISSUE TITLE
Add ability to disable draft/pre-beta specifications

### ISSUE THREAD

**Issue by chrispittman** [celtic-project/LTI-PHP#46]
We use this library in several production apps against the Canvas LMS, all of which went down simultaneously for us last week.  The culprit was some kind of bug or other downtime in Canvas's support for the draft "OIDC Login with LTI Client Side postMessages" specification, which this library added support for in version 4.10.0.  Canvas started failing to negotiate its side of the postMessages correctly, and the apps failed to launch as a result.  (Our solution was to roll all of our apps back to v4.9 temporarily; this may have been fixed in Canvas since then.)

Technically, that's a Canvas bug and not a Celtic LTI-PHP bug, but it was caused by us being unable to control our exposure to a draft spec and the instability around it.  It'd be great to have some kind of feature flag to enable this spec (and future draft or pre-beta specs), which is off by default; clients should be able to control whether they can afford to be on the bleeding edge or not.

**Comment by spvickers** [comment]
I pondered this when adding support for it and could not think of a reason why it might be necessary to disable it when offered, but I see that your example suggests otherwise.  My assumption had been that if it is offered then it should be working!

At present you can alter the delay before the check times out (see the documentation at https://github.com/celtic-project/LTI-PHP/wiki/Platform_storage) and I suspect a value of zero would effectively disable it, but I'll alter the code to remove this feature when the value is zero (or less).

Thanks for the suggestion.
