### ISSUE TITLE
Assignment & Grade Services (AGS) 2.0: Can I store tool-provided resourceId values in the lti2_resource_link table?

### ISSUE THREAD

**Issue by danhammari** [celtic-project/LTI-PHP#79]
Hi Stephen,

I'm working through the Assignment & Grade Services (AGS) 2.0 specification and want my tool to ask the platform to create a new grade book entry at the platform's grade book lineitems endpoint. I can user the ceLTIc project's `lti2_context` and `lti2_resource_link` tables to retrieve the user's `lti_context_id` and `lti_resource_link_id` values and extract the lineitems endpoint from their settings columns. I then have enough information to generate a new grade book lineitem by generating a `resourceId` value and posting it the lineitems endpoint.

[https://www.imsglobal.org/node/161981#creating-a-new-line-item](https://www.imsglobal.org/node/161981#creating-a-new-line-item)

The concern I have is that the platform does not return an `lti_resource_link_id` value for the new grade book lineitems entry, so I cannot create a new record for this grade book entry in the ceLTIc project's `lti2_resource_link` table. The platform does return a lineitem endpoint that I can use to directly query the newly-created grade book column. However, I cannot store this lineitem endpoint into the `lti2_resource_link` table with a null `lti_resource_link_id` value. Should I try to store the tool-generated `resourceId` value in the `lti_resource_link_id` column instead?

If the ceLTIc project's `lti2_resource_link` table isn't designed to track tool-generated `resourceId` values, then I can create a new table to store them. That will give me the ability to check whether I have already had the tool ask the platform to create a grade book entry for a tool `resourceId` as well as return the lineitem endpoint for that grade book entry. It might be nice to re-use the existing `lti2_resource_link` table for this purpose though.

Thanks in advance for your advice.
Sincerely,

Dan Hammari

**Comment by spvickers** [comment]
I assume you have seen the documentation at https://github.com/celtic-project/LTI-PHP/wiki/Line-Item-service which illustrates how you can use the library to manage line items.

The typical workflow is for a launch to occur from a resource link before you have access to its line items, so perhaps this is the issue with the platform you are using.  I would not expect to be creating a resource link entry in a tool based on the response from a LineItem service request.  But notwithstanding that, if the platform is not including a resourceLinkId property in its response to a request for line-items, then perhaps this means that the platform does not support such an association and just treats them as belonging to the context.  But since you are creating the line items, surely you can store the endpoint for each at the time you create them at which point you know the resource link for which they were created.

The library does not include any tables for line-item data, so you can either add one, or if your needs are quite simple you could use the setSetting/getSetting methods which are available for Platform, Context and ResourceLink objects.  By convention, tour settings should be given names with a prefix of a double underscore (__) to avoid clashes with normal settings and those added by the library (which are given a single underscore prefix).

HTH.

**Comment by spvickers** [comment]
Just a couple of other thoughts.  I assume that you are passing the resource link ID when creating the line-item; if not, that would explain its absence when requesting a list of line items.  To support those platforms which do not return resource link IDs, you could include this value as part of the resource ID.
